
let PROVIDE_PROJECT_ID_HERE = "123455667";

// --To get list of items--
export const TaskData = [
    {
        "status": "To Do",
        "statusId": 514,
        "issueList": [
            {
                "createdTime": "2024-05-25T07:52:23.000Z",
                "issue_no": "1",
                "project_name": "New Sample Project",
                "id": "48376",
                "issue_type_id": 1,
                "issue_status_id": 514,
                "description": "<p>New Task Description Here...</p>",
                "story_point_estimate": "",
                "timeLine": 1716623432000,
                "DueDate": 1716623432000,
                "sprint_id": 0,
                "module_id": null,
                "severity_id": null,
                "priority_id": 0,
                "Flagged_id": null,
                "project_id": `${PROVIDE_PROJECT_ID_HERE}`,
                "summary": "Task 1",
                "epic_id": null,
                "issue_labels_id": null,
                "labels": null,
                "assigned_user_id": null,
                "assigned_user": null,
                "attachment_id": null,
                "daysSinceAssigned": 0,
                "attachments": null,
                "attachments_date": null,
                "attachments_file_name": null,
                "Epic": null,
                "short_key": "NSP",
                "epic_color": null
            },
            {
                "createdTime": "2024-05-25T07:52:54.000Z",
                "issue_no": "2",
                "project_name": "New Sample Project",
                "id": "48377",
                "issue_type_id": 1,
                "issue_status_id": 514,
                "description": "<p>Task Description 2</p>",
                "story_point_estimate": "",
                "timeLine": 1716623450000,
                "DueDate": 1716623450000,
                "sprint_id": 0,
                "module_id": null,
                "severity_id": null,
                "priority_id": 0,
                "Flagged_id": null,
                "project_id": `${PROVIDE_PROJECT_ID_HERE}`,
                "summary": "Task 2",
                "epic_id": null,
                "issue_labels_id": null,
                "labels": null,
                "assigned_user_id": null,
                "assigned_user": null,
                "attachment_id": null,
                "daysSinceAssigned": 0,
                "attachments": null,
                "attachments_date": null,
                "attachments_file_name": null,
                "Epic": null,
                "short_key": "NSP",
                "epic_color": null
            },
            {
                "createdTime": "2024-05-25T07:53:11.000Z",
                "issue_no": "3",
                "project_name": "New Sample Project",
                "id": "48378",
                "issue_type_id": 1,
                "issue_status_id": 514,
                "description": "<p>Task Description 3</p>",
                "story_point_estimate": "",
                "timeLine": 1716623474000,
                "DueDate": 1716623474000,
                "sprint_id": 0,
                "module_id": null,
                "severity_id": null,
                "priority_id": 0,
                "Flagged_id": null,
                "project_id": `${PROVIDE_PROJECT_ID_HERE}`,
                "summary": "Task 3",
                "epic_id": null,
                "issue_labels_id": null,
                "labels": null,
                "assigned_user_id": null,
                "assigned_user": null,
                "attachment_id": null,
                "daysSinceAssigned": 0,
                "attachments": null,
                "attachments_date": null,
                "attachments_file_name": null,
                "Epic": null,
                "short_key": "NSP",
                "epic_color": null
            },
            {
                "createdTime": "2024-05-25T07:53:35.000Z",
                "issue_no": "4",
                "project_name": "New Sample Project",
                "id": "48379",
                "issue_type_id": 1,
                "issue_status_id": 514,
                "description": "<p>Task Description 4</p>",
                "story_point_estimate": "",
                "timeLine": 1716623501000,
                "DueDate": 1716623501000,
                "sprint_id": 0,
                "module_id": null,
                "severity_id": null,
                "priority_id": 0,
                "Flagged_id": null,
                "project_id": `${PROVIDE_PROJECT_ID_HERE}`,
                "summary": "Task 4",
                "epic_id": null,
                "issue_labels_id": null,
                "labels": null,
                "assigned_user_id": null,
                "assigned_user": null,
                "attachment_id": null,
                "daysSinceAssigned": 0,
                "attachments": null,
                "attachments_date": null,
                "attachments_file_name": null,
                "Epic": null,
                "short_key": "NSP",
                "epic_color": null
            }
        ],
        "issueListCount": 4
    },
    {
        "status": "IN PROGRESS",
        "statusId": 515,
        "issueList": [],
        "issueListCount": 0
    },
    {
        "status": "COMPLETED",
        "statusId": 516,
        "issueList": [],
        "issueListCount": 0
    }
]


// --To get details of currently selected item--
export const currentlySelectedItem = {
  success: "1",
  errorMessage: "",
  successMessage: "success",
  data: [
    {
      issueCloseStatus: 1,
      issue_no: "1",
      reporter_id: 403,
      reporterName: " Monkey D Luffy",
      reporter_email_id: "monkey.d.luffy@kaizokuonline.com",
      project_name: "New Sample Project",
      createdTime: "2024-05-25T07:52:23.000Z",
      id: "48376",
      issue_type_id: 1,
      issue_status_id: 514,
      description: "<p>New Task Description Here...</p>",
      story_point_estimate: "",
      timeLine: 1716623432000,
      DueDate: 1716623432000,
      sprint_id: 0,
      module_id: null,
      severity_id: null,
      priority_id: 0,
      Flagged_id: null,
      project_id: `${PROVIDE_PROJECT_ID_HERE}`,
      summary: "Task 1",
      Expected_Result: null,
      test_result: null,
      issue_labels_id: null,
      labels: null,
      assigned_user_id: null,
      assigned_user: null,
      attachment_id: null,
      attachments: null,
      attachments_date: null,
      attachments_file_name: null,
      Epic: null,
      short_key: "NSP",
      epic_color: null,
      epic_id: null,
      project_type: "Bug",
    },
  ],
  child: [],
  Comments: [],
  linkedIssue: [],
  version: [],
  issueStatus: [
    {
      id: 514,
      status_name: "To Do",
      created_on: "2024-05-25T07:52:04.000Z",
      created_by: 403,
      is_active: 1,
      project_id: `${PROVIDE_PROJECT_ID_HERE}`,
      order_no: 1,
      sub_status: 0,
      colorCode: null,
      test_case_status: 0,
    },
    {
      id: 515,
      status_name: "IN PROGRESS",
      created_on: "2024-05-25T07:52:04.000Z",
      created_by: 403,
      is_active: 1,
      project_id: `${PROVIDE_PROJECT_ID_HERE}`,
      order_no: 2,
      sub_status: 0,
      colorCode: null,
      test_case_status: 0,
    },
    {
      id: 516,
      status_name: "COMPLETED",
      created_on: "2024-05-25T07:52:04.000Z",
      created_by: 403,
      is_active: 1,
      project_id: `${PROVIDE_PROJECT_ID_HERE}`,
      order_no: 3,
      sub_status: 0,
      colorCode: null,
      test_case_status: 0,
    },
  ],
};
